# vim: ft=make tw=78 ts=4 sw=4 noet

# PKG_ROOT is the root of this package (i.e. git repository)
PKG_ROOT :=../..

.PHONY: default
default: libmercury_mpm

include ../Makefile.src_shared

.PHONY: clean
clean: mercury_mpm.clean

.PHONY: realclean
realclean: mercury_mpm.realclean
