# vim: ft=make tw=78 ts=4 sw=4 noet

include $(PKG_ROOT)/Make.options
include $(PKG_ROOT)/mpm.options

MI_TMPL := $(PKG_ROOT)/src/share/meta_info.template

.PHONY: distclean
distclean: realclean

include $(PKG_ROOT)/src/share/Makefile.generic
